name: alma_app
description: A new Flutter project with Clean Architecture by Abdalluh Essam
# Flutter version on machine: 3.32.8
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  dio:
  shared_preferences:
  easy_localization:
  intl:
  equatable:
  get_it:
  connectivity_plus: 
  cached_network_image:
  flutter_screenutil:
  flutter_animate:
  flutter_native_splash:
  firebase_crashlytics:
  animate_do:
  lottie:
  google_fonts:
  flutter_launcher_icons:
  animator:
  dartz:
  flutter_svg:
  cupertino_icons:
  firebase_messaging: ^16.0.0
  googleapis_auth: ^2.0.0
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
  mockito:
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lang/
